### ISSUE TITLE
Bottom overflowed with keyboard open, hiding password field

### ISSUE THREAD

**Issue by HugoHeneault** [TheAlphamerc/flutter_login_signup#1]
Hey there!

Thanks for this really cool flutter login screen app :)

On small devices when keyboard is opened it's overflowing a bit too much:

![image](https://user-images.githubusercontent.com/4112256/74422585-1fbbb680-4e4f-11ea-8dab-ed395f083ff3.png)

How could we fix it?

Cheers!

**Comment by TheAlphamerc** [comment]
Thanks for raising good issue. I have fixed it please take new clone or pull from master branch to see changes.
<img width="359" alt="Screenshot 2020-02-13 at 9 59 15 PM" src="https://user-images.githubusercontent.com/37103237/74456384-bf5b6200-4eac-11ea-9ccc-1526ffe4dba9.png">
