### ISSUE TITLE
 getting  this error can you pls help

### ISSUE THREAD

**Issue by shivpatil007** [TheAlphamerc/flutter_login_signup#8]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses 
or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':path_provider:extractDebugAnnotations'.     
> Could not resolve all files for configuration ':path_provider:lintClassPath'.
   > Could not download intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.5.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.5.0/intellij-core-26.5.0.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.5.0/intellij-core-26.5.0.jar'.
            > Remote host closed connection during handshake
   > Could not download kotlin-compiler.jar (com.android.tools.external.com-intellij:kotlin-compiler:26.5.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.5.0/kotlin-compiler-26.5.0.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.5.0/kotlin-compiler-26.5.0.jar'.
            > dl.google.com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.       

* Get more help at https://help.gradle.org

BUILD FAILED in 22m 27s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                      1352.2s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by TheAlphamerc** [comment]
Hi @shivpatil007 , I run this project after a long time and it still running without any error. Pls make sure you have active internet connection while compiling code.
